# Generated by Django 2.1.4 on 2019-01-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(help_text='Enter a brief description of the project', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a project type (e.g. Churn, Python, Neural Network)', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ManyToManyField(help_text='Select a type for this project', to='portfolio.Type'),
        ),
    ]
