# Generated by Django 2.1.4 on 2019-01-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.URLField(null=True),
        ),
    ]
